### ISSUE TITLE
The name 'm_typewriter' does not exist in the current context

### ISSUE THREAD

**Issue by randoomx8** [baba-s/TMP_Typewriter#1]
**Error:**
`Assets\test001.cs(10,9): error CS0103: The name 'm_typewriter' does not exist in the current context`

**My script:**
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using KoganeUnityLib;

public class test001 : MonoBehaviour
{
	void Start()
    {
        m_typewriter.Play
		(
			text        : "ABCDEFG HIJKLMN OPQRSTU",
			speed       : 5f,
			onComplete  : () => Debug.Log( "Complete !" )
		);
    }
}
```

_I have DoTween installed, latest version, fully functional._

What should I do?

**Comment by baba-s** [comment]
@randoomx8 

1. You attach a TMP_Typewriter to the GameObject of TextMesh Pro on Unity Editor.
2. Define `public TMP_Typewriter m_typewriter;` in "test001" class.
3. Assign the GameObject to which TMP_Typewriter is attached to "test001" class.

**Comment by randoomx8** [comment]
Thank you, I feel really stupid for not realizing that.
